#!/usr/bin/env bash
# Author: Alexander Epstein https://github.com/alexanderepstein

### Global vars
# Get the directory path where the current script is located
DIRECTORY="${0%/*}"
LIB="bash-snippets.lib"

ERR=0	# exit status

# source library, and exit on error
source "$DIRECTORY/$LIB" || {
	# don't use _Echo_Err; library not sourced!
	echo "$PROGRAM: failed to source '$LIB' library" >&2
	exit 3
}


### Function declaration
#
# get lyrics for song by artist
#
# Globals:
# 	artist: artist name
# 	song: song name
#
# Inputs: nothing
#
# Outputs:
# 	lyrics: lyrics text
#
# Returns:
# exit with error status if error occurred
Get_Lyrics() {

	# TODO
	# better url encoding 
	# https://stackoverflow.com/questions/11876353/url-encoding-a-string-in-bash-script
	# only wget support url encoding

	artist=$(echo "$artist" | sed -e 's/ /%20/g' -e 's/&/%26/g' -e 's/,/%2C/g' -e 's/-/%2D/g')
	  song=$(  echo "$song" | sed -e 's/ /%20/g' -e 's/&/%26/g' -e 's/,/%2C/g' -e 's/-/%2D/g')

	response=$(_HTTP_GET "https://api.lyrics.ovh/v1/$artist/$song")
	lyrics="$(_Access_Json_Element "$response" ".lyrics")"

	[[ $? -ne 0 ]] && { 
		_Echo_Err "$(_Access_Json_Element "$response" ".error")"
		exit 1
	}

	Print_Lyrics

}	# end of function Get_Lyrics


# print lyrics
#
# Globals:
# 	lyrics
#
# Inputs: nothing
# Outputs: nothing
# Returns: nothing
Print_Lyrics() { echo -e "$lyrics"; }


# print help message
#
# Globals:
# 	PROGRAM
#
# Inputs: nothing
# Outputs: nothing
# Returns: nothing
Help() {
	cat <<- EOF
	usage: $PROGRAM [-h|-u|-V] ARTIST SONG
	Fetch lyrics for song title.

	Mandatory positional arguments
	  ARTIST: Artist name
	    SONG: Song title

	Options
	  -h  display this help and exit
	  -u  display synopsis/brief usage and exit
	  -V  display tool version and exit

	Note:
	  arguments should be quoted
	  e.g. \`$PROGRAM 'artist' 'song name with space'\`
	EOF
}


### Parse cli option
while getopts ":-huV" opt; do
	case "$opt" in
		h ) Help; exit 0 ;;
		u ) _Usage; exit 0 ;;
		V ) echo "$VERSION"; exit 0 ;;

		### parse long option
		- )
			case "$OPTARG" in
				help ) Help; exit 0 ;;
				usage ) _Usage; exit 0 ;;

				* )
					_Echo_Err "Invalid option '--$OPTARG'"
					_Try_Help
					exit 1
				;;
			esac
		;;

		: )
			_Echo_Err "Option '-$OPTARG' requires an argument."
			exit 1
		;;

		* )
			_Echo_Err "$PROGRAM: Invalid option '-$OPTARG'"
			_Try_Help
			exit 1
		;;
	esac
done
shift $((OPTIND - 1))


## check if missing mandatory command line arguments
case $# in
	0 )
		_Echo_Err "$PROGRAM: missing artist name and song title"
		ERR=1
	;;

	1 )
		_Echo_Err "$PROGRAM: two few argument: missing artist name or title"
		ERR=1
	;;

	2 ) artist="$1"; song="$2" ;;

	* )
		_Echo_Err "$PROGRAM: two many arguments"
		ERR=1
	;;
esac

[[ $ERR -ne 0 ]] && {
	_Try_Help
	exit $ERR
}

_Check_If_All_Dep "jq"
_Check_Internet
Get_Lyrics

exit $ERR

