#!/usr/bin/env bash
# Author: 

### Global vars
# Get the directory path where the current script is located
DIRECTORY="${0%/*}"
LIB="bash-snippets.lib"

DETAIL=false	# detailed output flag
ERR=0	# exit status
KEY_LEN=0	# longest key string length
VAL_LEN=0
NCOL=80	# output line width


# source library, and exit on error
source "$DIRECTORY/$LIB" || {
	# don't use _Echo_Err; library not sourced!
	echo "$PROGRAM: failed to source '$LIB' library" >&2
	exit 3
}


# request movie info from OMDB API
#
# Globals:
# 	DETAIL
# 	ERR: set error to 1 on error (e.g title not found)
#
# Inputs:
# 	title
#
# Outputs:
# 	keys: array contain key string
# 	values: array contains values corresponded to keys
#
# Return: nothing
Get_Info() {

	# we used two arrays instead of associate array because associate array are unsorted
	declare -g -a keys values
	
	title="$(echo "$*" | tr ' ' '+')"

	# please consider using your own API key
	API_KEY="e3aeac39"
	PARAMETER="t=$title&apikey=$API_KEY"
	URL="http://www.omdbapi.com/?$PARAMETER"

	response="$(_HTTP_GET "$URL")"

	# check api response, if response was false, Print Error and exit
	check_res=$(_Access_Json_Element "$response" ".Response")
	if [[ "$check_res" == "False" ]]; then
		_Echo_Err $(Print_KV "Error" "$(_Access_Json_Element "$response" ".Error")")
		ERR=1
		return
	fi

	keys+=('title')
	values+=("$(_Access_Json_Element "$response" ".Title")")

	keys+=('year')
	values+=("$(_Access_Json_Element "$response" ".Year")")

	keys+=('runtime')
	values+=("$(_Access_Json_Element "$response" ".Runtime")")

	keys+=('imdb_rating')
	values+=("$(_Access_Json_Element "$response" ".imdbRating")")
	
	keys+=('rotten_tomatoes_rating')
	values+=("$(_Access_Json_Element "$response" ".Ratings[1].Value")")

	keys+=('rated')
	values+=("$(_Access_Json_Element "$response" ".Rated")")

	keys+=('genre')
	values+=("$(_Access_Json_Element "$response" ".Genre")")

	keys+=('director')
	values+=("$(_Access_Json_Element "$response" ".Director")")

	keys+=('actor')
	values+=("$(_Access_Json_Element "$response" ".Actors")")

	keys+=('plot')
	values+=("$(_Access_Json_Element "$response" ".Plot")")

	if $DETAIL; then
		keys+=('awards')
		values+=("$(_Access_Json_Element "$response" ".Awards")")

		keys+=('box_office')
		values+=("$(_Access_Json_Element "$response" ".BoxOffice")")

		keys+=('metacritic_rating')
		values+=("$(_Access_Json_Element "$response" ".Ratings[2].Value")")

		keys+=('production')
		values+=("$(_Access_Json_Element "$response" ".Production")")
	fi

	Print_Info

}	# end of function Get_Info


# print 'key: value' pair information
#
# Globals:
# 	KEY_LEN
# 	VAL_LEN
# 	NCOL
#
# Inputs:
# 	key
# 	value
# 
# Outputs: nothing
# Returns: nothing
Print_KV() {

	key="$1"
	val="$2"

	line_format="%${KEY_LEN}s %-${NCOL}s\n"

	# API response may contain 'null' as string or 'N/A', skip it
	[[ "${val,,}" == "null" || "${val^^}" == "N/A" || -z "$val" ]] && return

	if [[ ${#val} -le $VAL_LEN ]]; then
		printf "$line_format" "$key:" "$val"

	else
		printf "$line_format" "$key:" ' '
		while IFS= read -r line; do
			printf "$line_format" ' ' "$line"
		done < <(echo "$val" | fmt -w $VAL_LEN)
	fi

}	# end of function Print_KV


# prints title information
#
# Global: 
# 	keys
# 	values
#
# Input: nothing
# Output:
# 	KEY_LEN
# 	VAL_LEN
#
# Returns: nothing
Print_Info() {

	# get the length of longest key
	for key in "${keys[@]}"; do
		len=${#key}
		(( len > KEY_LEN )) && KEY_LEN=$len
	done
	KEY_LEN=$(( $KEY_LEN + 2 ))
	VAL_LEN=$(( NCOL - KEY_LEN ))

	for i in ${!keys[@]}; do
		key=${keys[$i]}
		key="${key^}"	# convert first character to upper case
		key="${key//_/ }"	# replace all under score with space
		Print_KV "$key" "${values[$i]}"
		#  paste -d ":\t" <(printf '%s\n' "${keys[@]}") <(printf '%s\n' "${values[@]}")
	done

}	# end of function Print_Info


# print help message
#
# Globals:
# 	PROGRAM
#
# Inputs: nothing
# Outputs: nothing
# Returns: nothing
Help() {

	cat <<- EOF
	usage: $PROGRAM [OPTION] TITLE ...
	Retrieve relevant information about a certain title.

	Option
	  -d, --detail		show detailed information
	  -h, --help		display help message and exit
	  -u, --usage		display brief usage and exit
	  -V, --version		display tool version and exit
	EOF
}	# end of function Help


### Parse cli option
while getopts ':-:dhuV' opt; do
	case "$opt" in
		d ) DETAIL=true ;;
		h ) Help; exit 0 ;;
		u ) _Usage; exit 0 ;;
		V ) echo "$VERSION"; exit 0 ;;

		### parse long option
		- )
			case "$OPTARG" in
				detail ) DETAIL=true ;;
				help ) Help; exit 0 ;;
				usage ) _Usage; exit 0 ;;
				version ) echo "$VERSION"; exit 0 ;;
				* )
					_Echo_Err "$PROGRAM: Invalid option '--$OPTARG'"
					_Try_Help
					exit 1
				;;
			esac
		;;

		* )
			_Echo_Err "$PROGRAM: Invalid option '-$OPTARG'"
			_Try_Help
			exit 1
		;;
	esac
done
shift $(( OPTIND - 1 ))


[[ $# -eq 0 ]] && {
	_Echo_Err "$PROGRAM: two few argument: missing title(s)"
	_Try_Help
	exit 1
}

_Check_If_All_Dep "jq" "fmt"
_Check_Internet

for title in "$@"; do Get_Info "$title"; done

exit $ERR

